Feat/stable funcs
brettinternet/react-cooked-bread pull request #15
Opened 2020-09-28 23:17 UTC by TomPridham

* makes the functions returned from `useActiveToasts` more stable to prevent infinite/unnecessary renders
* moves some tests into their parent describe blocks
* fixed a bug when maxToasts <= 0
* updated tests to condense some `act` blocks
* updated tests to use `inlineSnapshot` to make some of the checks a bit simpler

2020-09-29 00:02 UTC, TomPridham commented on packages/react-cooked-bread/src/active-toasts-hook.ts
> +              return []
i'm not sure how i feel about this. previously, having `maxToasts = 0` meant you could add an unlimited amount of toasts, because it would always fail the if statement. that seemed wrong. i don't really like how this turned out and feel like there should be a better way

2020-09-29 00:56 UTC, brettinternet requested changes
Thank you for your improvements and your PR!. See my comments about `maxToasts`

2020-09-29 00:56 UTC, brettinternet commented on packages/react-cooked-bread/src/active-toasts-hook.ts
> +  const removeToast = useCallback(
So ultimately the `useCallback` provided the stability?

2020-09-29 00:56 UTC, brettinternet commented on packages/react-cooked-bread/src/active-toasts-hook.ts
> +          return prevToasts
This is much more clear now.

2020-09-29 00:56 UTC, brettinternet commented on packages/react-cooked-bread/src/active-toasts-hook.ts
> +          if (typeof maxToasts === 'number' && maxToasts < prevToasts.length + 1) {
While it's an unlikely edge case, the following might befuddle this logic:

```js
typeof NaN === 'number'; // true 😒
```

We might consider either [`Number.isNaN`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isNaN) or [this](https://stackoverflow.com/a/1830844/6817437) popular suggestion. Perhaps for simplicity, we could also just revert back to checking if the value is falsy after coercing the value into a number (i.e. `maxToasts = Number(maxToasts)`).

2020-09-29 00:56 UTC, brettinternet commented on packages/react-cooked-bread/src/active-toasts-hook.ts
> +              return []
My intention was to have it so when `maxToasts` was `0` or `undefined` then there would be no maximum threshold imposed. The `maxToasts` is a bit opinionated because it will bump the oldest toast off the stack, so I believe the option should be given to the user.

The changes here now make it so that when `maxToasts === 0` then no toasts are rendered, however when `maxToasts === NaN` then toasts are allowed to stack infinitely. To keep it simple, I think we should only respect `maxToasts` when its value is a truthy number.

2020-09-29 00:56 UTC, brettinternet commented on packages/react-cooked-bread/src/active-toasts-hook.ts
> +      const id = options.id
Is there a benefit to the change you added with relocating `getId`?

2020-09-29 00:56 UTC, brettinternet commented on packages/react-cooked-bread/src/active-toasts-hook.ts
> +const checkForId = (id: string) => (t: ActiveToast) => t.id === id
Did you notice a benefit to removing this function to here?

The variable name for the function might be improved by indicating that it's finding/matching IDs.

2020-09-29 00:56 UTC, brettinternet commented on packages/react-cooked-bread/test/active-toasts-hook.test.ts
> -    const { result } = renderHook(() => useActiveToasts(0))
See comment above regarding `maxToasts` and a falsy value.

2020-09-29 00:56 UTC, brettinternet commented on packages/react-cooked-bread/test/active-toasts-hook.test.ts
> +    expect(result.current.toasts).toMatchInlineSnapshot(`
Great test improvement

2020-09-29 00:56 UTC, brettinternet commented on packages/react-cooked-bread/test/active-toasts-hook.test.ts
> +      result.current.removeToast(toastId)
Better, thank you

2020-09-29 00:56 UTC, brettinternet commented on packages/react-cooked-bread/test/active-toasts-hook.test.ts
> +utils.getId.mockImplementation(() => String(++id))
Is this to make `toMatchInlineSnapshot` ID values predictable?

2020-09-29 01:00 UTC, brettinternet commented on packages/react-cooked-bread/test/active-toasts-hook.test.ts
> +utils.getId.mockImplementation(() => String(++id))
Yes. This is a great improvement to the tests in order to ensure that `getId` is being invoked correctly in `useActiveToasts`.

2020-09-29 18:12 UTC, TomPridham commented on packages/react-cooked-bread/src/active-toasts-hook.ts
> +              return []
hmm. yeah. that makes sense. i'll revert that

2020-09-29 18:14 UTC, TomPridham commented on packages/react-cooked-bread/test/active-toasts-hook.test.ts
> +utils.getId.mockImplementation(() => String(++id))
yeah, it's to make them predictable across tests. that was also why i moved some of the `test` and `it` blocks into the main describe block. the beforeEach was only running in side the describe block so changing the order of any of the tests outside of it would have broken the tests

2020-09-30 16:14 UTC, TomPridham commented on packages/react-cooked-bread/src/active-toasts-hook.ts
> +const checkForId = (id: string) => (t: ActiveToast) => t.id === id
not really. i broke it out onto its own when i was trying to get rid of the `exists` function altogether.
something like `idMatches`? i wasn't sure what a good name would be

2020-09-30 16:14 UTC, TomPridham commented on packages/react-cooked-bread/src/active-toasts-hook.ts
> +  const removeToast = useCallback(
yes

2020-09-30 16:18 UTC, TomPridham commented on packages/react-cooked-bread/src/active-toasts-hook.ts
> +      const id = options.id
`getId` is only getting called once now instead of twice. i don't think this was strictly necessary, so i can't revert it if you want

2020-09-30 16:29 UTC, TomPridham commented on packages/react-cooked-bread/src/active-toasts-hook.ts
> +const checkForId = (id: string) => (t: ActiveToast) => t.id === id
i just reverted it. i was using it in more places when i was trying to get rid of `exists`, but it's only being used in two places as is

2020-09-30 17:57 UTC, brettinternet commented on packages/react-cooked-bread/src/active-toasts-hook.ts
> +      const id = options.id
I believe it should only have been called when `options.id` was falsy. I like your implementation just fine. I was just curious about explicit improvements.

2020-09-30 18:03 UTC, brettinternet requested changes
Minor suggestions

2020-09-30 18:03 UTC, brettinternet commented on packages/react-cooked-bread/src/active-toasts-hook.ts
> +          if (maxToasts && maxToasts < toasts.length + 1) {
```suggestion
          if (maxToasts && maxToasts < prevToasts.length + 1) {
```

I believe that should prevent having to include `toasts` in the dependency array (see lint warning below).

2020-09-30 18:03 UTC, brettinternet commented on packages/react-cooked-bread/src/active-toasts-hook.ts
> +  const exists = useCallback((id: Id) => toasts.some((t: ActiveToast) => t.id === id), [toasts])
I believe `ActiveToast` isn't necessary here and may be inferred.

2020-09-30 18:03 UTC, brettinternet commented on packages/react-cooked-bread/src/active-toasts-hook.ts
> +          const index = prevToasts.findIndex((t: ActiveToast) => t.id === id)
I believe this may be inferred as well.

2020-09-30 18:34 UTC, brettinternet approved these changes

2020-09-30 18:35 UTC, merged

2020-09-30 18:35 UTC, brettinternet commented
Thank you! @TomPridham

2020-09-30 18:35 UTC, brettinternet commented
Thank you!